Repository snowflakedb/snowflake-connector-python, pull requests merged in 2024-07, with the labels that each got.

#1986 SNOW-1266560: Add github merge gate port sp changes
  .github/pull_request_template.md
  .github/workflows/port_changes_to_sp.yml
Labels: NO-CHANGELOG-UPDATES

#1964 Python connector changes for server-side Snowpark
  src/snowflake/connector/connection.py
  src/snowflake/connector/cursor.py
Labels: NO-CHANGELOG-UPDATES

#1992 SNOW-1518775: fix connector fips docker image
  ci/docker/connector_test_fips/Dockerfile
Labels: NO-CHANGELOG-UPDATES

#1989 SNOW-1514764: Support Tracing in SPCS runtime
  src/snowflake/connector/network.py
Labels: NO-CHANGELOG-UPDATES

#1991 SNOW-1516350: disable oob telemetry
  src/snowflake/connector/telemetry_oob.py
  test/unit/test_telemetry_oob.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#1946 SNOW-806291: Fix Snowpark much slower than Spark Connector on Databricks (for collect() and toPandas())
  DESCRIPTION.md
  src/snowflake/connector/result_set.py
Labels: NO-CHANGELOG-UPDATES

#1993 SNOW-1511108 SQLAlchemy heartbeat frequency parsed as string
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  test/integ/test_connection.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2000 SNOW-1473577: Add comment for `internal_application_name` in connection parameters
  src/snowflake/connector/connection.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#1988 SNOW-1468259 Add connection timeout and read timeout to storage client request
  DESCRIPTION.md
  src/snowflake/connector/constants.py
  src/snowflake/connector/storage_client.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#1994 SNOW-1506571: make connector domain agnostic
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  src/snowflake/connector/connection_diagnostic.py
  src/snowflake/connector/constants.py
  src/snowflake/connector/network.py
  src/snowflake/connector/ocsp_snowflake.py
  src/snowflake/connector/ssl_wrap_socket.py
  src/snowflake/connector/url_util.py
  src/snowflake/connector/util_text.py
  test/integ/test_connection.py
  test/unit/test_connection.py
  test/unit/test_construct_hostname.py
  test/unit/test_ocsp.py
  test/unit/test_url_util.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2003 SNOW-1539600: Refactor structured type tests to explicitly set params
  test/integ/test_arrow_result.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2004 SNOW-1538754: Update keyring upper bound to 26
  DESCRIPTION.md
  setup.cfg
Labels: DO_NOT_PORT_CHANGES_TO_SP

#1996 SNOW-1526475: fix type hint for private_key
  DESCRIPTION.md
  src/snowflake/connector/connection.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2005 Bump python connector to 3.12.0
  DESCRIPTION.md
  src/snowflake/connector/version.py
  tested_requirements/requirements_310.reqs
  tested_requirements/requirements_311.reqs
  tested_requirements/requirements_312.reqs
  tested_requirements/requirements_38.reqs
  tested_requirements/requirements_39.reqs
Labels: DO_NOT_PORT_CHANGES_TO_SP
