Repository snowflakedb/snowflake-connector-python, pull requests merged in 2024-08, with the labels that each got.

#2012 Fix gcp test so that gcs downscoped is always enabled
  test/integ/test_put_get_with_gcp_account.py
Labels: NO-CHANGELOG-UPDATES

#2014 SNOW-1563453: remove oob telemetry usage in connector
  src/snowflake/connector/connection.py
  src/snowflake/connector/errors.py
  src/snowflake/connector/network.py
  src/snowflake/connector/ocsp_snowflake.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2017 Refactor default config location resolution to use pathlib instead of os
  DESCRIPTION.md
  src/snowflake/connector/sf_dirs.py
  test/unit/test_configmanager.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2021 SNOW-1620333: unpin cryptography and add deprecation detection
  DESCRIPTION.md
  setup.cfg
  test/unit/test_dependencies.py
  tox.ini
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2023 SNOW-1613751 remove reference to script `snowflake-export-certs`
  DESCRIPTION.md
  setup.cfg
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2022 SNOW-1571763 fix login timeout read pattern
  DESCRIPTION.md
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/auth/okta.py
  src/snowflake/connector/auth/webbrowser.py
  src/snowflake/connector/connection.py
  test/integ/test_connection.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2028 SNOW-1432591: update readme on disabling telemetry
  README.md
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2027 SNOW-1562604: enhance error handling when polling query result
  DESCRIPTION.md
  src/snowflake/connector/network.py
  test/integ/test_network.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2032 PATCH: Bumped up PythonConnector PATCH version from 3.12.0 to 3.12.1
  DESCRIPTION.md
  src/snowflake/connector/version.py
  tested_requirements/requirements_310.reqs
  tested_requirements/requirements_311.reqs
  tested_requirements/requirements_312.reqs
  tested_requirements/requirements_38.reqs
  tested_requirements/requirements_39.reqs
Labels: DO_NOT_PORT_CHANGES_TO_SP
