Repository snowflakedb/snowflake-connector-python, pull requests merged in 2024-10, with the labels that each got.

#2065 Fix a test to align with server side BCR
  test/integ/test_connection.py
Labels: NO-CHANGELOG-UPDATES

#2068 SNOW-1325701: Use scoped temp object in write pandas
  src/snowflake/connector/_utils.py
  src/snowflake/connector/bind_upload_agent.py
  src/snowflake/connector/pandas_tools.py
  test/integ/pandas/test_pandas_tools.py
  test/unit/test_bind_upload_agent.py
Labels: NO-CHANGELOG-UPDATES

#2072 SNOW-1540289: add test for max policy backoff time
  test/unit/test_backoff_policies.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2074 SNOW-799381: improve error message when hitting ssl related error
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  src/snowflake/connector/constants.py
  src/snowflake/connector/network.py
  test/unit/test_connection.py
  test/unit/test_util.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2058 SNOW-1657037: Remove secrets from debug logs.
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/secret_detector.py
  test/unit/test_log_secret_detector.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2060 SNOW-1650124: Pass Azure SAS Token via params
  src/snowflake/connector/azure_storage_client.py
  test/integ/test_put_get_with_azure_token.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2078 SNOW-1760173: fix test failure
  test/integ/test_connection.py
  test/unit/test_connection.py
Labels: NO-CHANGELOG-UPDATES

#2090 SNOW-1708720: Error is raised at debug level when not closing connection
  src/snowflake/connector/aio/_network.py
Labels: NO-CHANGELOG-UPDATES

#2088 SNOW-1760502 Update README.md
  README.md
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2092 SNOW-1313658: Verify timestamp bidings
  test/integ/test_bindings.py
Labels: NO-CHANGELOG-UPDATES
