Repository snowflakedb/snowflake-connector-python, pull requests merged in 2025-04, with the labels that each got.

#2241 SNOW-1789751: Pass GCS regional and virtual params
  DESCRIPTION.md
  src/snowflake/connector/file_transfer_agent.py
  src/snowflake/connector/gcs_storage_client.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2251 SNOW-1896089: Lower log level
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  src/snowflake/connector/cursor.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2249 SNOW-1825495 some usability issues after pentesting
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/auth/oauth_code.py
  src/snowflake/connector/token_cache.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2257 Fpawlowski/snow 2011595 snowflake connector for python logging presigned ur ls
  .github/workflows/build_test.yml
  .pre-commit-config.yaml
  test/integ/conftest.py
  test/integ/test_large_result_set.py
  test/integ/test_put_get_with_aws_token.py
  test/integ/test_put_get_with_azure_token.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2262 Snow 2011595 snowflake connector for python logging presigned ur ls
  DESCRIPTION.md
  src/snowflake/connector/__init__.py
  src/snowflake/connector/azure_storage_client.py
  src/snowflake/connector/cursor.py
  src/snowflake/connector/externals_utils/__init__.py
  src/snowflake/connector/externals_utils/externals_setup.py
  src/snowflake/connector/logging_utils/__init__.py
  src/snowflake/connector/logging_utils/filters.py
  src/snowflake/connector/secret_detector.py
  test/integ/conftest.py
  test/integ/test_large_result_set.py
  test/integ/test_put_get_with_aws_token.py
  test/integ/test_put_get_with_azure_token.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2260 Snow 1886670 Fix urllib3 vendored library
  .github/workflows/build_test.yml
  Dockerfile
  MANIFEST.in
  pyarrow-hw.py
  test/integ/test_put_get_with_aws_token.py
  test/integ/test_put_get_with_azure_token.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2254 SNOW-2027116 Allow for UUID encoding in SnowflakeRestful interface
  src/snowflake/connector/network.py
  test/unit/test_network.py
Labels: bug, NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2258 SNOW-1955965: Fix expired S3 credentials update
  DESCRIPTION.md
  src/snowflake/connector/file_transfer_agent.py
  src/snowflake/connector/s3_storage_client.py
  src/snowflake/connector/storage_client.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2264 NO-SNOW Add PAT to authenticators allowing empty username, remove handling of PAT in password field
  src/snowflake/connector/connection.py
  test/data/wiremock/mappings/auth/pat/invalid_token.json
  test/data/wiremock/mappings/auth/pat/successful_flow.json
  test/unit/test_programmatic_access_token.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2266 NO-SNOW Fix flaky query timeout test
  test/integ/test_cursor.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2268 SNOW-2040000 change tag to bptp-stable
  Jenkinsfile
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2255 SNOW-2028051 introduce a new client_fetch_threads connection parameter to decouple threads number limitations on fetching and pre-fetching
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  src/snowflake/connector/cursor.py
  test/integ/test_connection.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2267 Add default entra app ID for Snowflake
  src/snowflake/connector/wif_util.py
  test/unit/test_auth_workload_identity.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2253 Snow 2011595 Masking filter introduced on library levels
  .github/workflows/build_test.yml
  DESCRIPTION.md
  src/snowflake/connector/__init__.py
  src/snowflake/connector/azure_storage_client.py
  src/snowflake/connector/cursor.py
  src/snowflake/connector/externals_utils/__init__.py
  src/snowflake/connector/externals_utils/externals_setup.py
  src/snowflake/connector/logging_utils/__init__.py
  src/snowflake/connector/logging_utils/filters.py
  src/snowflake/connector/secret_detector.py
  test/integ/conftest.py
  test/integ/test_large_result_set.py
  test/integ/test_put_get_with_aws_token.py
  test/integ/test_put_get_with_azure_token.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2273 NO-SNOW Fetch wiremock in test_darwin.sh and test_windows.bat
  ci/test_darwin.sh
  ci/test_windows.bat
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2274 SNOW-2032699: Use GCS virtual url based on the stage response
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  src/snowflake/connector/cursor.py
  src/snowflake/connector/file_transfer_agent.py
  src/snowflake/connector/gcs_storage_client.py
  test/integ/test_connection.py
  test/unit/test_gcs_client.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2280 NO-SNOW acquiring a lock on local OCSP cache will use a timeout
  src/snowflake/connector/ocsp_snowflake.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2278 NO-SNOW update 3.14.1 release notes
  DESCRIPTION.md
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2281 Accept both v1 and v2 Entra ID issuer formats for WIF
  src/snowflake/connector/wif_util.py
  test/unit/test_auth_workload_identity.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2283 SNOW-2048239 revert zero timeout for oscp cache lock
  DESCRIPTION.md
  src/snowflake/connector/ocsp_snowflake.py
  test/unit/test_ocsp.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2284 NO-SNOW Update release date
  DESCRIPTION.md
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2286 SNOW-1993520 Patch python connector version bump
  DESCRIPTION.md
  src/snowflake/connector/version.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2294 Support client-side opt-in of Refresh Token Rotation in Snowflake OAuth
  src/snowflake/connector/auth/oauth_code.py
  src/snowflake/connector/connection.py
  test/unit/test_auth_oauth_auth_code.py
  test/unit/test_connection.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2295 SNOW-2055494 fix proper boto min versions
  DESCRIPTION.md
  setup.cfg
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2298 SNOW-2061664 flatten OAuth refresh_token and pkce parameters
  src/snowflake/connector/connection.py
  test/unit/test_oauth_token.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2299 SNOW-2067577 OCSP: stop certificates chain traversal as soon as a trusted one met
  DESCRIPTION.md
  src/snowflake/connector/ocsp_asn1crypto.py
  src/snowflake/connector/tool/dump_ocsp_response.py
  tox.ini
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2292 SNOW-2057503 allow only whitelisted schemes for OAuth url parameters
  src/snowflake/connector/connection.py
  src/snowflake/connector/errorcode.py
  test/unit/test_oauth_token.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2301 SNOW-2068668 Move OAuth out of PrPr flag
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  test/unit/test_oauth_token.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2302 SNOW-2057797 Minor python connector version bump
  DESCRIPTION.md
  src/snowflake/connector/version.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2305 SNOW-2057797 Update requirements files
  tested_requirements/requirements_310.reqs
  tested_requirements/requirements_311.reqs
  tested_requirements/requirements_312.reqs
  tested_requirements/requirements_313.reqs
  tested_requirements/requirements_39.reqs
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP
