Repository snowflakedb/snowflake-connector-python, pull requests merged in 2025-08, with the labels that each got.

#2336 SNOW-2119489: Add support for interval types in json format
  DESCRIPTION.md
  src/snowflake/connector/arrow_context.py
  src/snowflake/connector/converter.py
  src/snowflake/connector/interval_util.py
  src/snowflake/connector/nanoarrow_cpp/ArrowIterator/IntervalConverter.cpp
  src/snowflake/connector/nanoarrow_cpp/ArrowIterator/IntervalConverter.hpp
  test/integ/test_arrow_result.py
  test/integ/test_interval_types.py
Labels: interval_datatype

#2453 SNOW-2229745: Move oauth_type into client_environment
  DESCRIPTION.md
  src/snowflake/connector/auth/_oauth_base.py
  test/unit/test_auth_oauth_auth_code.py
  test/unit/test_oauth_token.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2459 Fix bug in AWS sovereign partition support
  src/snowflake/connector/wif_util.py
  test/csp_helpers.py
  test/unit/test_auth_workload_identity.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2429 Snow 2203079 http traffic without interception with adapter
  .pre-commit-config.yaml
  ci/pre-commit/check_no_native_http.py
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/auth/_oauth_base.py
  src/snowflake/connector/auth/okta.py
  src/snowflake/connector/auth/webbrowser.py
  src/snowflake/connector/auth/workload_identity.py
  src/snowflake/connector/connection.py
  src/snowflake/connector/connection_diagnostic.py
  src/snowflake/connector/network.py
  src/snowflake/connector/ocsp_snowflake.py
  src/snowflake/connector/platform_detection.py
  src/snowflake/connector/result_batch.py
  src/snowflake/connector/session_manager.py
  src/snowflake/connector/ssl_wrap_socket.py
  src/snowflake/connector/storage_client.py
  src/snowflake/connector/telemetry_oob.py
  src/snowflake/connector/wif_util.py
  test/csp_helpers.py
  test/integ/pandas_it/test_arrow_pandas.py
  test/integ/test_connection.py
  test/integ/test_cursor.py
  test/integ/test_large_result_set.py
  test/unit/mock_utils.py
  test/unit/test_auth_okta.py
  test/unit/test_auth_workload_identity.py
  test/unit/test_check_no_native_http.py
  test/unit/test_detect_platforms.py
  test/unit/test_proxies.py
  test/unit/test_result_batch.py
  test/unit/test_retry_network.py
  test/unit/test_session_manager.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2470 SNOW-2047992 Include VCRedist library into Windows wheels and get rid of PyArrow version constraint
  DESCRIPTION.md
  ci/build_windows.bat
  setup.cfg
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2478 [BUILD] Add win_arm64 platform support
  .github/workflows/build_test.yml
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2491 NO-SNOW disable yet failing Win-ARM64 tests
  .github/workflows/build_test.yml
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2489 SNOW-2268606-regression-3.17.0-unexplained-errors-in-connecting-to-IMDS-from-3.17.0-leads-to-connection-failures-and-excessive-logging-works-with-3.16.0
  DESCRIPTION.md
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/platform_detection.py
  src/snowflake/connector/session_manager.py
  test/integ/test_connection.py
  test/unit/test_session_manager.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2492 NO-SNOW: fix flaky tests on invalid proxy
  test/integ/test_connection.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2485 SNOW-2272485: CICD reconfiguration
  .github/workflows/build_test.yml
  .github/workflows/parameters/public/jenkins_test_parameters.py.gpg
  .github/workflows/parameters/public/rsa_keys/rsa_key_python_aws.p8.gpg
  .github/workflows/parameters/public/rsa_keys/rsa_key_python_azure.p8.gpg
  .github/workflows/parameters/public/rsa_keys/rsa_key_python_gcp.p8.gpg
  Jenkinsfile
  ci/test_darwin.sh
  ci/test_docker.sh
  ci/test_fips.sh
  ci/test_linux.sh
  ci/test_windows.bat
  test/integ/conftest.py
  tox.ini
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2490 SNOW-2268606 zero timeout disables endpoint-based cloud platform detection
  DESCRIPTION.md
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/auth/okta.py
  src/snowflake/connector/auth/webbrowser.py
  src/snowflake/connector/platform_detection.py
  test/integ/test_connection.py
  test/unit/test_detect_platforms.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2487 SNOW-00000 : Update CODEOWNERS
  .github/CODEOWNERS
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2495 SNOW-2274695 Bump up to 3.17.2 version
  DESCRIPTION.md
  src/snowflake/connector/version.py
  tested_requirements/requirements_310.reqs
  tested_requirements/requirements_311.reqs
  tested_requirements/requirements_312.reqs
  tested_requirements/requirements_313.reqs
  tested_requirements/requirements_39.reqs
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2488 SNOW-2161716: Fix config file permissions check and skip warning using env variable
  DESCRIPTION.md
  src/snowflake/connector/config_manager.py
  test/unit/test_configmanager.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2503 SNOW-2160718 adjust ec2 IP in WIF tests, limit docker resources
  ci/test_wif.sh
  ci/wif/parameters/parameters_wif.json.gpg
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2510 Update WIF integration tests to verify authenticated username + prepare for impersonation
  ci/test_wif.sh
  ci/wif/parameters/parameters_wif.json.gpg
  test/wif/test_wif.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP
