Repository snowflakedb/snowflake-connector-python, pull requests merged in 2025-03, with the labels that each got.

#2190 3.14-Update Requirements
  DESCRIPTION.md
  src/snowflake/connector/version.py
  tested_requirements/requirements_310.reqs
  tested_requirements/requirements_311.reqs
  tested_requirements/requirements_312.reqs
  tested_requirements/requirements_39.reqs
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2191 Update version 3.14.0 in requirements
  tested_requirements/requirements_310.reqs
  tested_requirements/requirements_311.reqs
  tested_requirements/requirements_312.reqs
  tested_requirements/requirements_39.reqs
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2192 SNOW-1959352 disable test_connection::test_bogus
  test/integ/test_connection.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2182 SNOW-1940996 no-op auth for Stored Proc
  src/snowflake/connector/auth/__init__.py
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/auth/by_plugin.py
  src/snowflake/connector/auth/no_auth.py
  src/snowflake/connector/connection.py
  src/snowflake/connector/network.py
  test/integ/test_connection.py
  test/unit/test_auth_no_auth.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2137 SNOW-1825621 OAuth code flow PKCE support
  src/snowflake/connector/auth/oauth_code.py
  src/snowflake/connector/connection.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2193 SNOW-1960930: Update GH runner to ubuntu-latest
  .github/workflows/build_test.yml
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2194 Update DESCRIPTION.md - add next release notes header stub
  DESCRIPTION.md
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2199 I think it's time to retire from snowflake-connector-python
  .github/CODEOWNERS
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2201 skip decfloat test in olddriver tests
  test/integ/test_decfloat.py
  test/unit/test_converter.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2165 SNOW-1825610: Initial OCSP Deprecation
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  src/snowflake/connector/constants.py
  src/snowflake/connector/ocsp_snowflake.py
  src/snowflake/connector/ssl_wrap_socket.py
  test/integ/test_connection.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2196 SNOW-1927118 Enable wiremock tests on Jenkins
  ci/docker/connector_test/Dockerfile
  ci/set_base_image.sh
  ci/test_linux.sh
  test/unit/test_wiremock_client.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2205 SNOW-1825495 Improve HTTP server targeted at serving OAuth redirects with timeouts and tests
  src/snowflake/connector/auth/_http_server.py
  test/unit/test_auth_callback_server.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2209 SNOW-1977987 fix LOB size change impacted integration tests
  test/integ/test_cursor.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2210 SNOW-1825624: Refactor token cache before applying security changes
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/cache.py
  src/snowflake/connector/token_cache.py
  test/integ/sso/test_unit_mfa_cache.py
  test/unit/test_linux_local_file_cache.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2183 SNOW-1944162 Add tests for programmatic access token
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  test/data/wiremock/mappings/auth/pat/invalid_token.json
  test/data/wiremock/mappings/auth/pat/successful_flow.json
  test/data/wiremock/mappings/generic/snowflake_disconnect_successful.json
  test/unit/test_programmatic_access_token.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2215 Cancel older builds on GH Actions
  .github/workflows/build_test.yml
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2203 Add support for workload identity federation
  setup.cfg
  src/snowflake/connector/auth/__init__.py
  src/snowflake/connector/auth/by_plugin.py
  src/snowflake/connector/auth/workload_identity.py
  src/snowflake/connector/connection.py
  src/snowflake/connector/constants.py
  src/snowflake/connector/errorcode.py
  src/snowflake/connector/network.py
  src/snowflake/connector/wif_util.py
  test/csp_helpers.py
  test/unit/conftest.py
  test/unit/test_auth_workload_identity.py
  test/unit/test_connection.py
  tox.ini
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2212 SNOW-1917302 refresh token and token cache support in OAuth authorization code flow
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/auth/_http_server.py
  src/snowflake/connector/auth/oauth_code.py
  src/snowflake/connector/connection.py
  src/snowflake/connector/constants.py
  src/snowflake/connector/network.py
  test/data/wiremock/mappings/auth/oauth/authorization_code/new_tokens_after_failed_refresh.json
  test/data/wiremock/mappings/auth/oauth/authorization_code/successful_auth_after_failed_refresh.json
  test/data/wiremock/mappings/auth/oauth/authorization_code/successful_flow.json
  test/data/wiremock/mappings/auth/oauth/refresh_token/refresh_failed.json
  test/data/wiremock/mappings/auth/oauth/refresh_token/refresh_successful.json
  test/data/wiremock/mappings/generic/snowflake_login_failed.json
  test/unit/test_oauth_token.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2219 SNOW-1949054: Reenable to_file test
  test/integ/test_cursor.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2221 NO-SNOW: Run test when targeting branches other than main
  .github/workflows/build_test.yml
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2222 SNOW-1915375: disable license precommit hook
  .pre-commit-config.yaml
  license_header.txt
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2214 SNOW-1825624: Secure file token cache
  src/snowflake/connector/file_lock.py
  src/snowflake/connector/token_cache.py
  test/unit/test_linux_local_file_cache.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2198 SNOW-1963078 Port _upload / _download / _upload_stream / _download_st…
  src/snowflake/connector/connection.py
  src/snowflake/connector/cursor.py
  src/snowflake/connector/direct_file_operation_utils.py
  test/integ/test_connection.py
  test/unit/test_cursor.py
Labels: NO-CHANGELOG-UPDATES

#2231 Replace return with raise in error check
  src/snowflake/connector/auth/workload_identity.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2232 SNOW-1825621 added a retry logic for binding OAuth http server to a port
  src/snowflake/connector/auth/_http_server.py
  src/snowflake/connector/connection.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2234 jira creation ownership (to another support group)
  .github/workflows/jira_issue.yml
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2235 SNOW-1825495 reuse existing parameter to enable token cache
  src/snowflake/connector/connection.py
  test/unit/test_oauth_token.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2236 SNOW-2007887: improve error message handling related to timeout
  DESCRIPTION.md
  src/snowflake/connector/cursor.py
  test/integ/test_cursor.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2237 SNOW-1825495 use secret detector mask for variable logs
  src/snowflake/connector/auth/_oauth_base.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2233 SNOW-1789751: Add GCP regional and virtual endpoints support
  DESCRIPTION.md
  src/snowflake/connector/azure_storage_client.py
  src/snowflake/connector/connection.py
  src/snowflake/connector/cursor.py
  src/snowflake/connector/file_transfer_agent.py
  src/snowflake/connector/gcs_storage_client.py
  src/snowflake/connector/s3_storage_client.py
  test/integ/test_connection.py
  test/unit/test_gcs_client.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2227 SNOW-1989239 - prevent silent failures on nano-arrow conversion
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.cpp
  src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.hpp
  src/snowflake/connector/nanoarrow_cpp/ArrowIterator/nanoarrow_arrow_iterator.pyx
  src/snowflake/connector/result_batch.py
  test/helpers.py
  test/integ/pandas/test_unit_arrow_chunk_iterator.py
  test/integ/test_cursor.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2239 Snow-1763673 python3.13 support
  .github/workflows/build_test.yml
  .github/workflows/create_req_files.yml
  .pre-commit-config.yaml
  DESCRIPTION.md
  Jenkinsfile
  README.md
  ci/build_darwin.sh
  ci/build_docker.sh
  ci/build_linux.sh
  ci/build_windows.bat
  ci/docker/connector_build/Dockerfile
  ci/docker/connector_test/Dockerfile
  ci/docker/connector_test_fips/Dockerfile
  ci/docker/connector_test_lambda/Dockerfile313
  ci/docker/connector_test_lambda/Dockerfile38
  ci/docker/connector_test_lambda/app.py
  ci/test_darwin.sh
  ci/test_docker.sh
  ci/test_fips.sh
  ci/test_fips_docker.sh
  ci/test_lambda_docker.sh
  ci/test_linux.sh
  ci/test_windows.bat
  setup.cfg
  src/snowflake/connector/connection.py
  src/snowflake/connector/converter.py
  src/snowflake/connector/gzip_decoder.py
  src/snowflake/connector/nanoarrow_cpp/ArrowIterator/nanoarrow_ipc.c
  test/conftest.py
  test/integ/conftest.py
  test/integ/pandas/test_pandas_tools.py
  test/integ/test_arrow_result.py
  test/integ/test_vendored_urllib.py
  test/unit/test_ocsp.py
  tox.ini
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2244 SNOW-1825495 address shutdown errors on already closed socket
  src/snowflake/connector/auth/_http_server.py
  src/snowflake/connector/auth/oauth_code.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP
