Repository snowflakedb/snowflake-connector-python, pull requests merged in 2025-01, with the labels that each got.

#2127 SNOW-1868288 log level to debug in chunk rowcount logging
  DESCRIPTION.md
  src/snowflake/connector/cursor.py
  test/integ/test_cursor.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2117 SNOW-1848371 adding connection.is_valid to perform connection validation on TCP/IP and Session levels
  DESCRIPTION.md
  src/snowflake/connector/connection.py
  test/integ/test_connection.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2134 Support base64-encoded DER private keys
  DESCRIPTION.md
  src/snowflake/connector/auth/keypair.py
  src/snowflake/connector/connection.py
  test/integ/test_key_pair_authentication.py
  test/unit/test_auth_keypair.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2136 SNOW-1882588 Allow Empty Sql Text when Dataframe Ast is Presented
  src/snowflake/connector/cursor.py
Labels: NO-CHANGELOG-UPDATES

#2138 SNOW-1882588 Add Test for PR 2136
  test/unit/test_cursor.py
Labels: NO-CHANGELOG-UPDATES

#2139 Update CODEOWNERS
  .github/CODEOWNERS
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2141 release 3.13.0
  DESCRIPTION.md
  src/snowflake/connector/version.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2144 bump gh action
  .github/workflows/create_req_files.yml
  tested_requirements/requirements_310.reqs
  tested_requirements/requirements_311.reqs
  tested_requirements/requirements_312.reqs
  tested_requirements/requirements_39.reqs
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2146 remove 38 reqs file
  tested_requirements/requirements_38.reqs
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2151 pin qemu used for arm64 linux wheels
  .github/workflows/build_test.yml
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2149 Update CODEOWNERS
  .github/CODEOWNERS
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2154 SNOW-1902019: Python CVEs january batch
  src/snowflake/connector/auth/_auth.py
  src/snowflake/connector/cache.py
  src/snowflake/connector/encryption_util.py
  src/snowflake/connector/file_util.py
  src/snowflake/connector/ocsp_snowflake.py
  src/snowflake/connector/storage_client.py
  src/snowflake/connector/util_text.py
  test/extras/run.py
  test/unit/test_ocsp.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2155 SNOW-1902019: Python CVEs january batch 2
  src/snowflake/connector/cursor.py
  src/snowflake/connector/pandas_tools.py
  test/integ/pandas/test_pandas_tools.py
Labels: NO-CHANGELOG-UPDATES, DO_NOT_PORT_CHANGES_TO_SP

#2152 Release version 3.13.1
  DESCRIPTION.md
  src/snowflake/connector/version.py
  tested_requirements/requirements_310.reqs
  tested_requirements/requirements_311.reqs
  tested_requirements/requirements_312.reqs
  tested_requirements/requirements_39.reqs
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2158 Changed not to use scoped temp stage
  DESCRIPTION.md
  src/snowflake/connector/pandas_tools.py
  src/snowflake/connector/version.py
  test/integ/pandas/test_pandas_tools.py
  tested_requirements/requirements_310.reqs
  tested_requirements/requirements_311.reqs
  tested_requirements/requirements_312.reqs
  tested_requirements/requirements_39.reqs
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2160 SNOW-1891253 bump pyopenssl upper boundary to <26.0.0 from <25.0.0
  DESCRIPTION.md
  setup.cfg
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2112 delete workarround for pyton2.7
  DESCRIPTION.md
  src/snowflake/connector/connection.py
Labels: DO_NOT_PORT_CHANGES_TO_SP

#2163 SNOW-1886670 pin pyarrow
  DESCRIPTION.md
  setup.cfg
Labels: DO_NOT_PORT_CHANGES_TO_SP
